# Generated by Django 4.2.29 on 2026-03-11 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta'), ('CHEQUE', 'Cheque'), ('OTRO', 'Otro')], default='EFECTIVO', max_length=15)),
                ('tipo', models.CharField(choices=[('ANTICIPO', 'Anticipo'), ('PARCIAL', 'Parcial'), ('LIQUIDACION', 'Liquidación')], default='PARCIAL', max_length=12)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('fecha_pago', models.DateField()),
                ('notas', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
